Implement generator for collecting serializers
NoobDevTv/NonSucking.Framework.Extension pull request #20
Opened 2022-01-11 10:48 UTC by jvbsl

Calls collected generators in priority order
Parameter to include or exclude specific generators(Per default all generators are included)

I heard you like generators, so I made a generator for your generator

2022-01-12 18:15 UTC, susch19 requested changes
Namespace not fitting the project name

2022-01-12 18:15 UTC, susch19 commented on NonSucking.Framework.Serialization.SerializerCollector/SerializeGeneratorCollector.cs
> +namespace NonSucking.Framework.Serialization.Generator;
Why doe the namespace differ from the project name?

2022-01-12 18:27 UTC, susch19 approved these changes

2022-01-14 13:23 UTC, Gallimathias approved these changes

2022-01-14 13:24 UTC, Gallimathias commented
I like the generator for generator. But we should find a way to generate things like this with a generator :P

2022-01-14 13:55 UTC, merged