Added serialization of a few known types
NoobDevTv/NonSucking.Framework.Extension pull request #22
Opened 2022-01-21 23:12 UTC by jvbsl

* Implemented ability to add arbitrary source code files to projects using this generator
* Implemented check if constant types(templates) where already added(e.g. with reference by another project using this generator) and only add them when necessary
* Fix enum serializer for enums outside of current namespace
* Added binary reader extensions(added to the project using this generator) to be able to read a full Span<byte>
* Added serialization and deserialization of System.Guid struct type
* Added serialization and deserialization of System.Numerics.BigInteger struct type
* Added serialization and deserialization of System.Net.IPAddress struct type

2022-01-27 17:55 UTC, susch19 approved these changes

2022-02-05 17:41 UTC, Gallimathias requested changes

2022-02-05 17:41 UTC, Gallimathias commented on NonSucking.Framework.Serialization/NoosonGenerator.cs
> +                            .WithUsings(usings.ToArray())
hätte man das Array nicht gleich oben machen können?

2022-02-05 19:40 UTC, Gallimathias approved these changes

2022-02-05 19:41 UTC, merged