Fixed serialization of top level types inheriting from types serializ…
NoobDevTv/NonSucking.Framework.Extension pull request #28
Opened 2022-02-08 18:32 UTC by jvbsl

…able by the serializer

* Rewrote base serializer to actually use the best matching serializer logic, instead of a separated implementation of a property serializer
* Removed VisitInfo, as only the TypeSymbol of it was in use
* Propagate included serializers mask through the serializers to be able to exclude serializers for the top level "this"/"ret"
* In MemberInfo.FullName exclude "this." as a prefix
* In turn refactored the base serialization logic to be less redundant

2022-02-08 20:51 UTC, susch19 approved these changes, later dismissed
Looks good, but the retun in Order by can be shortened and than you wouldn't even need the attr variable and it could be made into one line.
Rest ist just the typical == null and is null :)

2022-02-08 20:51 UTC, susch19 commented on NonSucking.Framework.Serialization/Serializers/KnownSimpleTypeSerializer.cs
> +                    if (addressFamilySer == null)
```suggestion
                    if (addressFamilySer is null)
```

2022-02-08 20:51 UTC, susch19 commented on NonSucking.Framework.Serialization/Serializers/KnownSimpleTypeSerializer.cs
> +                    if (addressFamilySer == null)
```suggestion
                    if (addressFamilySer is null)
```

2022-02-08 20:51 UTC, susch19 commented on NonSucking.Framework.Serialization/Serializers/PublicPropertySerializer.cs
> +                if (propCode == null)
```suggestion
                if (propCode is null)
```

2022-02-08 20:51 UTC, susch19 commented on NonSucking.Framework.Serialization/Serializers/PublicPropertySerializer.cs
> +                                     if (attr == null)
```suggestion
                                    
```

2022-02-08 20:51 UTC, susch19 commented on NonSucking.Framework.Serialization/Serializers/PublicPropertySerializer.cs
> +                                         return int.MaxValue;
```suggestion
                                         
```

2022-02-08 20:51 UTC, susch19 commented on NonSucking.Framework.Serialization/Serializers/PublicPropertySerializer.cs
> +                                     return (int)attr.ConstructorArguments[0].Value!;
```suggestion
                                     return (int)attr?.ConstructorArguments[0].Value ?? int.MaxValue;
```

2022-02-08 20:51 UTC, susch19 commented on NonSucking.Framework.Serialization/Serializers/PublicPropertySerializer.cs
> +                if (propCode == null)
```suggestion
                if (propCode is null)
```

2022-02-09 08:58 UTC, susch19 commented on NonSucking.Framework.Serialization/Serializers/PublicPropertySerializer.cs
> +                                     return (int)attr.ConstructorArguments[0].Value!;
Best case new: 17,48357685 ticks
Worst case old: 0,00000925 ticks

2022-02-09 12:38 UTC, susch19 submitted a review, later dismissed

2022-03-10 19:32 UTC, Gallimathias requested changes

2022-03-10 19:32 UTC, Gallimathias commented on NonSucking.Framework.Serialization/Serializers/KnownSimpleTypeSerializer.cs
> +        GeneratedSerializerCode statements, NoosonGenerator.SerializerMask includedSerializers)
Warum ist die SerializerMask eigentlich Nested?

2022-03-10 19:32 UTC, Gallimathias commented on NonSucking.Framework.Serialization/Serializers/PublicPropertySerializer.cs
> +                statements.Statements.AddRange(propCode.ToMergedBlock());
```suggestion
                var propCode = GenerateStatementsForMember(prop, context, MethodType.Deserialize);
                
                if (propCode is null)
                    continue;
                    
                statements.Statements.AddRange(propCode.ToMergedBlock());
```

2022-03-11 18:06 UTC, Gallimathias approved these changes

2022-03-11 18:43 UTC, merged